name: Prebuild iOS folder

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: npm install

      - name: Run prebuild for iOS
        run: npx expo prebuild --platform ios

      - name: Upload iOS folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-folder
          path: ios
