name: Prebuild iOS folder

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: npm install

      - name: Run prebuild for iOS
        run: npx expo prebuild --platform ios

      - name: Check if GH_PAT secret exists
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "❌ GH_PAT is NOT set."
            exit 1
          else
            echo "✅ GH_PAT is set."
          fi

      - name: Commit & Push ios folder
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add ios folder via CI
          file_pattern: ios/*
          commit_user_name: Expo Prebuild Bot
          commit_user_email: action@github.com
          token: ${{ secrets.GH_PAT }}
